- plugin-script-nashorn/build.gradle
- plugin-script-nashorn/src/main/java/io/kestra/plugin/scripts/nashorn/Eval.java
- plugin-script/src/main/java/io/kestra/plugin/scripts/Eval.java
As it is no longuer integrated inside Java 17.
This is a pre-requisite to upgrade to Java 17.
> feat: use Nashorn from the library

- plugin-script-shell/src/main/java/io/kestra/plugin/scripts/shell/Script.java
- plugin-script/src/main/java/io/kestra/plugin/scripts/exec/scripts/runners/DefaultLogConsumer.java
- plugin-script/src/main/java/io/kestra/plugin/scripts/exec/scripts/runners/DockerScriptRunner.java
- plugin-script/src/test/java/io/kestra/plugin/scripts/runners/LogConsumerTest.java
> fix(script): No longer splitting too long logs on Docker runner

- plugin-script-jython/src/main/java/io/kestra/plugin/scripts/jython/FileTransform.java
- plugin-script-node/src/main/java/io/kestra/plugin/scripts/node/Script.java
- plugin-script-powershell/src/main/java/io/kestra/plugin/scripts/powershell/Script.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Commands.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Script.java
- plugin-script-r/src/main/java/io/kestra/plugin/scripts/r/Script.java
- plugin-script-shell/src/main/java/io/kestra/plugin/scripts/shell/Commands.java
- plugin-script-shell/src/main/java/io/kestra/plugin/scripts/shell/Script.java
closes https://github.com/kestra-io/plugin-scripts/issues/51
closes https://github.com/kestra-io/kestra.io/issues/367 (we can add more documentation later on if we see demand for it)
> (docs) outputDir and more examples

- plugin-script-julia/src/main/java/io/kestra/plugin/scripts/julia/Commands.java
- plugin-script-julia/src/main/java/io/kestra/plugin/scripts/julia/Script.java
- plugin-script-node/src/main/java/io/kestra/plugin/scripts/node/Commands.java
- plugin-script-node/src/main/java/io/kestra/plugin/scripts/node/Script.java
- plugin-script-powershell/src/main/java/io/kestra/plugin/scripts/powershell/Commands.java
- plugin-script-powershell/src/main/java/io/kestra/plugin/scripts/powershell/Script.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Commands.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Script.java
- plugin-script-python/src/test/java/io/kestra/plugin/scripts/python/ScriptTest.java
- plugin-script-r/src/main/java/io/kestra/plugin/scripts/r/Commands.java
- plugin-script-r/src/main/java/io/kestra/plugin/scripts/r/Script.java
- plugin-script-shell/src/main/java/io/kestra/plugin/scripts/shell/Commands.java
- plugin-script-shell/src/main/java/io/kestra/plugin/scripts/shell/Script.java
- plugin-script-shell/src/test/java/io/kestra/plugin/scripts/shell/CommandsTest.java
- plugin-script-shell/src/test/java/io/kestra/plugin/scripts/shell/ScriptTest.java
- plugin-script/src/main/java/io/kestra/plugin/scripts/exec/AbstractExecScript.java
> fix: allow setting docker options via task defaults

- .gitignore
- plugin-script/build.gradle
- plugin-script/src/main/java/io/kestra/plugin/scripts/exec/scripts/models/DockerOptions.java
- plugin-script/src/main/java/io/kestra/plugin/scripts/exec/scripts/runners/DockerScriptRunner.java
- plugin-script/src/main/java/io/kestra/plugin/scripts/exec/scripts/runners/DockerService.java
> feat(docker): introduce docker build plugin

- README.md
> fix(docs): Fixed a typo

- plugin-script-node/src/test/java/io/kestra/core/tasks/scripts/NodeTest.java
- plugin-script-python/src/test/java/io/kestra/core/tasks/scripts/PythonTest.java
- plugin-script-python/src/test/java/io/kestra/plugin/scripts/python/ScriptTest.java
- plugin-script-shell/src/test/java/io/kestra/core/tasks/scripts/AbstractBashTest.java
- plugin-script-shell/src/test/java/io/kestra/plugin/scripts/shell/CommandsTest.java
- plugin-script/src/main/java/io/kestra/core/tasks/scripts/ScriptOutput.java
- plugin-script/src/main/java/io/kestra/plugin/scripts/exec/scripts/models/ScriptOutput.java
- plugin-script/src/main/java/io/kestra/plugin/scripts/exec/scripts/runners/CommandsWrapper.java
- plugin-script/src/main/java/io/kestra/plugin/scripts/exec/scripts/runners/DockerScriptRunner.java
- plugin-script/src/main/java/io/kestra/plugin/scripts/exec/scripts/runners/ProcessBuilderScriptRunner.java
- plugin-script/src/main/java/io/kestra/plugin/scripts/exec/scripts/services/ScriptService.java
- plugin-script/src/test/java/io/kestra/core/tasks/scripts/ScriptOutputTest.java
- plugin-script/src/test/java/io/kestra/plugin/scripts/exec/scripts/models/ScriptOutputTest.java
> feat(script): allow to pass outputs when script failed (kestra-io/kestra#2407)

- gradle.properties
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Commands.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Script.java
Corrected the python script flow examples
> Correct python script examples

- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Commands.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Script.java
https://github.com/kestra-io/examples/blob/main/dockerfiles/kestrapy.Dockerfile
> fix: change to a default image that has kestra libs included

- plugin-script-julia/src/main/java/io/kestra/plugin/scripts/julia/Commands.java
- plugin-script-julia/src/main/java/io/kestra/plugin/scripts/julia/Script.java
- plugin-script-node/src/main/java/io/kestra/plugin/scripts/node/Commands.java
- plugin-script-node/src/main/java/io/kestra/plugin/scripts/node/Script.java
- plugin-script-powershell/src/main/java/io/kestra/plugin/scripts/powershell/Commands.java
- plugin-script-powershell/src/main/java/io/kestra/plugin/scripts/powershell/Script.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Commands.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Script.java
- plugin-script-r/src/main/java/io/kestra/plugin/scripts/r/Commands.java
- plugin-script-r/src/main/java/io/kestra/plugin/scripts/r/Script.java
- plugin-script-ruby/src/main/java/io/kestra/plugin/scripts/ruby/Commands.java
- plugin-script-ruby/src/main/java/io/kestra/plugin/scripts/ruby/Script.java
- plugin-script-shell/src/main/java/io/kestra/plugin/scripts/shell/Commands.java
- plugin-script-shell/src/main/java/io/kestra/plugin/scripts/shell/Script.java
Related to https://github.com/kestra-io/kestra/pull/3834
> feat(): new targetOS property

- plugin-script-groovy/src/main/java/io/kestra/plugin/scripts/groovy/FileTransform.java
Closes https://github.com/kestra-io/docs/issues/1466
> feat(docs): add groovy filetransform example using jackson library

- plugin-script-r/src/main/java/io/kestra/plugin/scripts/r/Script.java
Closes https://github.com/kestra-io/kestra/issues/4170
> fix(example): correct the R script example

- plugin-script/src/main/java/io/kestra/core/tasks/scripts/AbstractBash.java
Because it creates locally directories.
> fix(plugin-sript): bash task cannot run with a volume

- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Script.java
> Fixed typo in Python Script Docs

- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Script.java
Updated the doc for the Python task since {{ outputDir }} is now deprecated.
Examples have been tested within Kestra. Flows are running successfully.
Note that this is not a replacement for unit tests but rather a way to demonstrate how the changes work in a real-life scenario, as the end-user would experience them.
Remove this section if this change applies to all flows or to the documentation only. -->
---
Thank you for your contribution. ❤️  -->
> Doc fix for Python script task - {{ outputDir }} is deprecated

- plugin-script-jbang/src/main/java/io/kestra/plugin/scripts/jbang/Commands.java
- plugin-script-jbang/src/main/java/io/kestra/plugin/scripts/jbang/Script.java
- plugin-script-julia/src/main/java/io/kestra/plugin/scripts/julia/Commands.java
- plugin-script-julia/src/main/java/io/kestra/plugin/scripts/julia/Script.java
- plugin-script-node/src/main/java/io/kestra/plugin/scripts/node/Commands.java
- plugin-script-node/src/main/java/io/kestra/plugin/scripts/node/Script.java
- plugin-script-powershell/src/main/java/io/kestra/plugin/scripts/powershell/Commands.java
- plugin-script-powershell/src/main/java/io/kestra/plugin/scripts/powershell/Script.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Commands.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Script.java
- plugin-script-r/src/main/java/io/kestra/plugin/scripts/r/Commands.java
- plugin-script-r/src/main/java/io/kestra/plugin/scripts/r/Script.java
- plugin-script-ruby/src/main/java/io/kestra/plugin/scripts/ruby/Commands.java
- plugin-script-ruby/src/main/java/io/kestra/plugin/scripts/ruby/Script.java
- plugin-script-shell/src/main/java/io/kestra/plugin/scripts/shell/Commands.java
- plugin-script-shell/src/main/java/io/kestra/plugin/scripts/shell/Script.java
Depends on --> https://github.com/kestra-io/kestra/pull/6800
> fix: add runContext in inject default and render image

- build.gradle
- gradle.properties
> fix: remove slf4j fixed version

- plugin-script-julia/src/main/java/io/kestra/plugin/scripts/julia/Commands.java
- plugin-script-julia/src/main/java/io/kestra/plugin/scripts/julia/Script.java
- plugin-script-node/src/main/java/io/kestra/core/tasks/scripts/Node.java
- plugin-script-node/src/main/java/io/kestra/plugin/scripts/node/Commands.java
- plugin-script-node/src/main/java/io/kestra/plugin/scripts/node/Script.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Commands.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Script.java
- plugin-script-r/src/main/java/io/kestra/plugin/scripts/r/Script.java
- plugin-script/src/main/java/io/kestra/core/tasks/scripts/AbstractBash.java
- plugin-script/src/main/java/io/kestra/core/tasks/scripts/ScriptOutput.java
#https://github.com/kestra-io/plugin-scripts/issues/233
---
---
> feat(#233)!:remove warningOnError behavior

- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/AbstractPythonExecScript.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Commands.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Script.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/internals/PythonBasedPlugin.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/internals/PythonDependenciesResolver.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/internals/PythonEnvironmentManager.java
- plugin-script-python/src/test/java/io/kestra/plugin/scripts/python/ScriptTest.java
This commit fixes an issue on python cache restoration, and includes some refactoring
> fix(python): remove built-in requirements and fix cache restore

- plugin-script-node/src/main/java/io/kestra/plugin/scripts/node/Script.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Commands.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Script.java
- plugin-script-shell/src/main/java/io/kestra/plugin/scripts/shell/Commands.java
Helps solve https://github.com/kestra-io/docs/issues/2573
> docs(scripts): fix incorrectly indented examples

- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Commands.java
closes https://github.com/kestra-io/plugin-scripts/issues/113
> fix: replace conda with uv

- plugin-script-groovy/src/main/java/io/kestra/plugin/scripts/groovy/Commands.java
- plugin-script-groovy/src/main/java/io/kestra/plugin/scripts/groovy/Script.java
- plugin-script-groovy/src/test/java/io/kestra/plugin/scripts/groovy/CommandsTest.java
- plugin-script-groovy/src/test/java/io/kestra/plugin/scripts/groovy/RunnerTest.java
- plugin-script-groovy/src/test/java/io/kestra/plugin/scripts/groovy/ScriptTest.java
- plugin-script-groovy/src/test/resources/sanity-checks/all_groovy.yaml
> feat(groovy): add groovy Commands and Script tasks

- plugin-script-groovy/src/main/java/io/kestra/plugin/scripts/groovy/Eval.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Commands.java
- plugin-script-python/src/main/java/io/kestra/plugin/scripts/python/Script.java
> docs(): fix trailing spaces in examples
